### ISSUE TITLE
How to use the LaTeX features

### ISSUE THREAD

**Issue by physicophilic** [Iron-E/nvim-typora#1]
Hi, can you give an example on how to do LaTeX with this plugin?

I need added snippet functionality in Typora for my LaTeX, and well, this plugin claims to do a "live" rendering as I type in vim, (if I understand it right) 
which would be extremely beneficial to me.

I tried using the plugin, but I cannot see at all how this can be done. Launching Typora.snippet_mode() doesn't do anything.

By the way, I also noticed that there is a capitalization issue in the docs: typora.open (claimed) doesn't work, but Typora.open does.

can you please give a short example?

**Comment by Iron-E** [comment]
Thanks for the issue report! I'll do my best to support your use case.

> this plugin claims to do a "live" rendering

Yes— although I hope the wording doesn't misconvey what I mean. Typora live renders as you type; this plugin allows for you to easily open files in Typora, from within Neovim. You can do that like so:

```lua
-- Lua function
local typora = require('typora')
typora.open(<file>)

-- Lua command
vim.cmd('Typora <file>')
```

```vim
" Vimscript function
call typora#open(<file>)
" Vimscript command
Typora <file>
```

Where `<file>` is the path to the markdown file you want to open.

> Launching `Typora.snippet_mode()` doesn't do anything.

It should… what version of Neovim are you using? I can run:

```lua
local typora = require('typora')
-- lua function
typora.snippet_mode()
-- lua command
vim.cmd('TyporaMode')
```

…or:

```vim
" Vimscript Function
call typora#snippet_mode()
" Vimscript Command
TyporaMode
```

And both launch the mode.

> `typora.open` (claimed) doesn't work, but `Typora.open` does.

The first part of this comment about `typora.open()` applies here too. If I use `Typora.open()` (with a capital `T`) it throws errors at me.

Does it actually do nothing or does it give you some kind of error message in response?

___

The big thing that will help me debug this further is confirming the Neovim version. I'll be happy to go from there!

**Comment by physicophilic** [comment]
I am using neovim 0.5; I don't know where I can get versions beyond that, but if they exist and are needed, I would be ready to use them.

Firstly,
>Typora live renders as you type; 

You mean type in vim, right? Typora has an excellent math live preview, and I wanted to augment it with my Ultisnips from vim. If that is possible, I am very interested in this. 

Next, sorry, I have no idea where you are typing this code. These are not editor commands as I have checked, and the other place I could guess would be init.vim. 

I am novice at understanding plugins in vim, and in fact, I downloaded neovim for this project only.  I have never used Lua before.

Thanks for your help, but I need a little more of it!

**Comment by Iron-E** [comment]
I've been meaning to make some screen capture demos for this project, I think now would be the perfect time to do it. I'm going to research screen capture utilities for my operating system, and I'll add them to the README. Once they're there it should hopefully be a good demonstration for how to use this plugin!

And no worries about being new. We were all there ;)

I'll hopefully have those videos up either today or this weekend.

___

Edit: To be clear you have the correct Neovim version.

I'm entering these commands in a few places:

* The Vimscript functions are used with `:call` in the editor or in an `init.vim` (like you mentioned). Either will work (not shown in the demo, but can be seen [here](https://github.com/Iron-E/nvim-typora/blob/master/ftplugin/markdown/commands.vim#L8)).
* The Lua functions are used with `:lua require('typora')` in the editor or in an `init.vim` (not shown in the demo, but can be seen [here](https://github.com/Iron-E/nvim-typora/blob/master/autoload/typora.vim#L9)).
* The editor commands are run from pressing the `:` key (shown in the demo).

**Comment by Iron-E** [comment]
I completed the demo. You can watch it [here](https://github.com/Iron-E/nvim-typora#demo). Let me know if it answers any of the questions, or which ones remain after watching.

**Comment by Iron-E** [comment]
@physicophilic Do you still need support with this ticket?

**Comment by physicophilic** [comment]
Sorry, I got busy. 

I tested it. If I don't use your plugin, and just open typora in a new window and try to edit via vim, it works, but thanks to your plugin, this functionality has become a lot better. Vim doesn't ask for reloading the file unless actually any change in Typora window has been made; earlier even if I clicked Typora window, Vim would ask for a reload. Great help.

Second, I still cannot get your snippets to pop up like you do in your screencast. You use :TyporaMode and then probably press tab or something to make a list appear. However for me, no list appears, and if I press enter there, I get --TABLE-- automatically.

**Comment by Iron-E** [comment]
Thanks for the update! I think we're all a bit busier lately…

As for the popup, it is from Neovim's `wildmenu` setting. Try using the following settings and it should show up:

```vim
:set wildmenu
:set wildcharm=<C-z>
:set wildmode=longest:full,full

:set wildignorecase
:set wildignore+=*.pyc,*.cache,*.min.*
:set wildignore+=*/.git/**/*,*/node_modules/**/*
:set wildignore=*.swp,*.bak
```

Other than that, can you tell me if you have [`nvim-libmodal`](https://github.com/Iron-E/nvim-libmodal) installed? You can do that by telling me what happens when you do the following:

```vim
:lua print(vim.inspect(require('libmodal')))
```

* If an error occurs, it isn't installed.
* If a long string of text shows up about `Indicator`s and `api`s, it worked.

**Comment by physicophilic** [comment]
>Thanks for the update! I think we're all a bit busier lately…

Main work should be given priority! 

I used your wildmenu settings, but still a list of snippets doesn't show up on `:TyporaMode`.  My `:colorscheme` wildmenu does work however, so there's something wrong.

```
:lua print(vim.inspect(require('libmodal')))
```

gave a long list starting with an indicator and no errors, so I guess it is installed.

**Comment by Iron-E** [comment]
Followup question: if you use the `:TyporaMode` command, does a little indicator show up? It should look like this:

![Indicator](https://user-images.githubusercontent.com/36409591/96745410-a0a35880-13b5-11eb-8ffc-b058eec3229b.png)

If there is, that means that `:TyporaMode` has initialized and is waiting for a command. You can verify this by typing "help" and hitting enter:

![Help Page](https://user-images.githubusercontent.com/36409591/96745692-ef50f280-13b5-11eb-924b-0353b9d09344.png)

If you see both of these menus, then that means it should be working. All you have to do is one of two things:

1. Begin to type the name of a snippet/shortcut and then hit enter.
2. Hit `<Tab>` to cycle through the snippets and hit enter to select one.

Also note that there are completions for the snippets, so you can type "Diagram", hit `<Tab>`, and all options containing that string will appear.

___

Let me know if any of this works for you.

**Comment by physicophilic** [comment]
Thanks a lot for your replies. 
> Followup question: if you use the :TyporaMode command, does a little indicator show up? It should look like this:

Sorry to report that the indicator doesn't show for me. The second menu doesn't appear either.

I have now started to suspect that this is an appimage related issue. I am using nvim.appimage for 0.5 version right now. I usually use normal vim for my daily work, but for testing this plugin I go to this appimage.

Maybe if I build 0.5 nvim from source and spend some time on making my init.vim suitable, it will work?

**Comment by Iron-E** [comment]
It's possible— I had some issues with the appimage too. Here's a minimal configuration you can use to debug your own:

```vim
" ## Begin Plugin Loading
call plug#begin('/home/adamz/.local/share/nvim/plugged')

" Plug nvim-libmodal and nvim-typora
Plug 'https://github.comIron-E/nvim-libmodal.git'
Plug 'https://github.comIron-E/nvim-typora.git'

" Plug plasticboy's markdown
Plug 'https://github.com/plasticboy/vim-markdown.git'

" ## Terminate plugin loading
call plug#end()
```

All of the features of this plugin work with only these lines in your `init.vim`. If you save the above as "minrc.vim" and then run this command:

```shell
nim -u minrc.vim -c TyporaMode foo.md
```

…it should tell you whether or not it's going to work. __Note__ that for any of this plugin's features to load you have to be in a Markdown file.

___

Let me know how this works for you!

**Comment by Iron-E** [comment]
It's possible— I had some issues with the appimage too. Here's a minimal configuration you can use to debug your own:

```vim
" ## Begin Plugin Loading; change the path if you need to
call plug#begin('~/.local/share/nvim/plugged')

" Plug nvim-libmodal and nvim-typora
Plug 'https://github.com/Iron-E/nvim-libmodal.git'
Plug 'https://github.com/Iron-E/nvim-typora.git'

" Plug plasticboy's markdown (optional but desirable)
Plug 'https://github.com/plasticboy/vim-markdown.git'

" ## Terminate plugin loading
call plug#end()
```

All of the features of this plugin work with only these lines in your `init.vim`. If you save the above as "minrc.vim" and then run this command:

```shell
nim -u minrc.vim -c TyporaMode foo.md
```

…it should tell you whether or not it's going to work. __Note__ that for any of this plugin's features to load you have to be in a Markdown file.

___

Let me know how this works for you!
